# 목적: 문서에서 법적규제사항 키워드를 찾아 플래그 배열 생성
REG_PATTERNS = {
    "제조금지물질":      [r"제조\s*금지", r"prohibited\s*to\s*manufacture"],
    "제조허가대상물질":  [r"제조\s*허가", r"manufacturing\s*permit"],
    "노출기준설정대상물질":[r"노출기준 설정", r"occupational\s+exposure\s+limit"],
    "작업환경측정대상유해인자":[r"작업환경\s*측정\s*대상", r"workplace\s*environment\s*measurement"],
    "특수건강진단대상유해인자":[r"특수\s*건강\s*진단\s*대상", r"special\s*health\s*examination"],
    "특별관리물질":      [r"특별\s*관리\s*물질"],
    "허용기준설정대상 유해인자":[r"허용기준\s*설정"],
    "공정안전관리 대상물질":[r"공정안전관리", r"PSM", r"process\s*safety\s*management"],
    "영업비밀명칭 제외물질":[r"영업비밀.*제외"],
    "국소배기장치 안전검사 대상물질":[r"국소\s*배기\s*장치.*안전\s*검사"],
    "기초화학물질":      [r"기초\s*화학\s*물질", r"basic\s*chemicals?"],
    "유독물질":          [r"유독\s*물질", r"toxic\s*substance"],
    "허가물질":          [r"허가\s*물질", r"authorized\s*substance"],
    "제한물질":          [r"제한\s*물질", r"restricted\s*substance"],
    "금지물질":          [r"금지\s*물질", r"prohibited\s*substance"],
    "사고대비물질":      [r"사고\s*대비\s*물질"],
    "배출량조사대상화학물질":[r"(배출량|PRTR).*(조사|대상)"],
    "PRTR1군":           [r"PRTR\s*1\s*군|PRTR\s*Group\s*1"],
    "PRTR2군":           [r"PRTR\s*2\s*군|PRTR\s*Group\s*2"],
    "등록대상기준화학물질":[r"등록\s*대상\s*기준\s*화학물질"],
    "중점관리물질":      [r"중점\s*관리\s*물질", r"priority\s*management\s*substance"],
}
